In [1]:
import cv2
import numpy as np

In [2]:
img = cv2.imread('./data/src/grapes.jpg')
h, w = img.shape[:2]
dx, dy = 30, 30

In [3]:
afn_mat = np.float32([[1, 0, dx],[0, 1, dy]])
img_afn = cv2.warpAffine(img, afn_mat, (w, h))

In [4]:
cv2.imshow('trans', img_afn)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
rot_mat = cv2.getRotationMatrix2D((w/2, h/2), 40, 1)
img_afn2 = cv2.warpAffine(img, rot_mat, (w, h))
cv2.imshow('rotation', img_afn2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
img = cv2.imread('./data/src/drive.jpg')
h, w = img.shape[:2]
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
per1 = np.float32([[100, 500], [300, 500], [300, 100], [100, 100]])
per2 = np.float32([[100, 500], [300, 500], [280, 200], [150, 200]])

psp_matrix = cv2.getPerspectiveTransform(per1, per2)
img_psp = cv2.warpPerspective(img, psp_matrix, (w, h))

In [10]:
cv2.imshow('psp', img_psp)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
kernel = np.ones((3,3 )) / 9.0

In [12]:
kernel

array([[0.11111111, 0.11111111, 0.11111111],
       [0.11111111, 0.11111111, 0.11111111],
       [0.11111111, 0.11111111, 0.11111111]])

In [13]:
img = cv2.imread('./data/src/Lena.jpg', 0)

In [14]:
img_ker1 = cv2.filter2D(img, -1, kernel)

In [15]:
cv2.imshow('img', img_ker1)
cv2.imshow('src', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:
kernel2 = np.zeros((3, 3))
kernel2[0, 0] = 1
kernel2[1, 0] = 2
kernel2[2, 0] = 1
kernel2[0, 2] = -1
kernel2[1, 2] = -2
kernel2[2, 2] = -1

In [17]:
kernel2

array([[ 1.,  0., -1.],
       [ 2.,  0., -2.],
       [ 1.,  0., -1.]])

In [20]:
img_ker2 = cv2.filter2D(img, -1, kernel2)

In [21]:
cv2.imshow('img', img_ker2)
cv2.imshow('src', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [22]:
img = cv2.imread('./data/src/buildings.jpg')

In [23]:
img_blur = cv2.blur(img, (3, 3))

In [24]:
cv2.imshow('img', img)
cv2.imshow('blur', img_blur)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [25]:
img_ga = cv2.GaussianBlur(img, (9, 9), 2)

In [26]:
cv2.imshow('img', img_ga)
cv2.imshow('src', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [27]:
img_me = cv2.medianBlur(img, 5)

In [28]:
cv2.imshow('img', img_me)
cv2.imshow('src', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [29]:
img_bi = cv2.bilateralFilter(img, 20, 30, 30)

In [30]:
cv2.imshow('img', img_bi)
cv2.imshow('src', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [31]:
img = cv2.imread('./data/src/Lena.jpg', 0)
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [32]:
img_sobelx = cv2.Sobel(img, cv2.CV_32F, 1, 0, ksize=3)
img_sobely = cv2.Sobel(img, cv2.CV_32F, 0, 1, ksize=3)

In [33]:
img_sobelx

array([[   0.,   -4.,   -6., ...,  -72., -174.,    0.],
       [   0.,   -1.,   -5., ...,  -68., -176.,    0.],
       [   0.,    3.,   -5., ...,  -58., -169.,    0.],
       ...,
       [   0.,   31.,   14., ...,   -1.,  -12.,    0.],
       [   0.,   51.,   26., ...,    6.,    9.,    0.],
       [   0.,   58.,   28., ...,   10.,   20.,    0.]], dtype=float32)

In [36]:
img_sobelx = cv2.convertScaleAbs(img_sobelx)
img_sobely = cv2.convertScaleAbs(img_sobely)

In [35]:
img_sobelx

array([[  0,   4,   6, ...,  72, 174,   0],
       [  0,   1,   5, ...,  68, 176,   0],
       [  0,   3,   5, ...,  58, 169,   0],
       ...,
       [  0,  31,  14, ...,   1,  12,   0],
       [  0,  51,  26, ...,   6,   9,   0],
       [  0,  58,  28, ...,  10,  20,   0]], dtype=uint8)

In [37]:
cv2.imshow('x', img_sobelx)
cv2.imshow('y', img_sobely)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [38]:
img_lap = cv2.Laplacian(img, cv2.CV_32F)
img_lap = cv2.convertScaleAbs(img_lap)

In [40]:
img_lap *= 2
cv2.imshow('lap', img_lap)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [41]:
img_blur = cv2.GaussianBlur(img, (3, 3), 2)
img_lap2 = cv2.Laplacian(img_blur, cv2.CV_32F)
img_lap2 = cv2.convertScaleAbs(img_lap2)

In [42]:
img_lap *= 2
cv2.imshow('lap', img_lap2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [43]:
img = cv2.imread('./data/src/Lena.jpg', 0)
img_canny = cv2.Canny(img, 10, 100)
cv2.imshow('img', img_canny)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [44]:
img_canny = cv2.Canny(img, 100, 200)
cv2.imshow('img', img_canny)
cv2.waitKey(0)
cv2.destroyAllWindows()